# Generated by Django 4.2.4 on 2023-10-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_create_post_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_post',
            options={'verbose_name': 'Добавити пост', 'verbose_name_plural': 'Добавити пост'},
        ),
    ]
